[project]
name = "gm-dapp"
authors = []
description = "Social dApp on Stacks"
telemetry = true
requirements = []
epoch = "latest"

[contracts.gm-social]
path = "contracts/gm-social.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
